apiVersion: apps/v1
kind: Deployment
metadata:
  name: viraloop-api
  labels:
    app: viraloop-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: viraloop-api
  template:
    metadata:
      labels:
        app: viraloop-api
    spec:
      containers:
      - name: api
        image: viraloop-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://viraloop:viraloop@pgbouncer.default.svc.cluster.local:6432/viraloop"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672/"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: viraloop-worker
  labels:
    app: viraloop-worker
spec:
  # Replicas managed by KEDA HPA
  replicas: 1
  selector:
    matchLabels:
      app: viraloop-worker
  template:
    metadata:
      labels:
        app: viraloop-worker
    spec:
      containers:
      - name: worker
        image: viraloop-worker:latest
        env:
        - name: DATABASE_URL
          value: "postgresql://viraloop:viraloop@pgbouncer.default.svc.cluster.local:6432/viraloop"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672/"
        - name: BRIDGE_URL
          value: "http://viraloop-api.default.svc.cluster.local:8000/api/bridge"
        volumeMounts:
        - name: media-storage
          mountPath: /home/jmyoon312/viral_loop_media
      volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: viraloop-pvc
