import { VLStandardBlueprint, VLLayerObject } from '@/types/blueprint';

/**
 * 4대 원형 프리셋(Archetype) 초기화 팩토리
 * 썰형, 군림보, 인스타, 클래식 고유의 레이어 트리를 생성합니다.
 */

export function createSsulArchetype(id: string = 'archetype_ssul', name: string = '썰형 기본 원형'): VLStandardBlueprint {
  const layers: VLLayerObject[] = [
    // 1. 메인 배경 비디오/이미지
    {
      id: 'layer_bg_video',
      name: '배경 비디오',
      kind: 'media',
      mediaRole: 'main_background',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 960, width: 1080, height: 1920, rotation: 0, scale: 1, origin: 'center', zIndex: 1 },
      inMs: 0,
      outMs: null,
      opacity: 1,
      assetId: 'sample1',
      fit: 'cover',
      focus: [0.5, 0.5],
      motion: { type: 'none', strength: 0.1, durationMs: 3000 },
      clipFromMs: 0,
    },
    // 2. 상단 커뮤니티 헤더바 (노란 헤더 띠)
    {
      id: 'layer_ssul_header_bg',
      name: '상단 헤더바',
      kind: 'shape',
      shapeRole: 'hook_band',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 120, width: 1080, height: 140, rotation: 0, scale: 1, origin: 'center', zIndex: 10 },
      inMs: 0,
      outMs: null,
      opacity: 1,
      fillColor: '#FFCC00',
      borderRadius: 0,
      borderWidth: 0,
    },
    // 3. 헤더 채널명 텍스트
    {
      id: 'layer_ssul_header_text',
      name: '헤더 채널명',
      kind: 'text',
      textRole: 'badge',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 120, width: 900, height: 80, rotation: 0, scale: 1, origin: 'center', zIndex: 11 },
      inMs: 0,
      outMs: null,
      opacity: 1,
      content: '익명의 커뮤니티 레전드 썰',
      fontFamily: 'NotoSansKR-Bold',
      fontSize: 42,
      fontColor: '#1A1A1A',
      letterSpacing: -1,
      lineHeight: 1.2,
      textAlign: 'center',
      borderRadius: 0,
      padding: [0, 0, 0, 0],
      accumulateMode: false,
    },
    // 4. 단락별 자막 누적 영역 (본문 텍스트)
    {
      id: 'layer_ssul_body_accumulate',
      name: '누적 본문 자막',
      kind: 'text',
      textRole: 'subtitle_narrative',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 520, width: 960, height: 480, rotation: 0, scale: 1, origin: 'center', zIndex: 15 },
      inMs: 0,
      outMs: null,
      opacity: 1,
      content: '회사에서 겪은 역대급 황당 썰\n장면마다 줄이 하나씩 쌓여요',
      fontFamily: 'NotoSansKR-Bold',
      fontSize: 52,
      fontColor: '#FFFFFF',
      letterSpacing: -1,
      lineHeight: 1.4,
      textAlign: 'left',
      stroke: { color: '#000000', width: 6 },
      shadow: { color: 'rgba(0,0,0,0.8)', blur: 12, offsetX: 0, offsetY: 4 },
      borderRadius: 16,
      padding: [24, 24, 24, 24],
      backgroundColor: 'rgba(0,0,0,0.4)',
      accumulateMode: true,
      emojiSlot: {
        enabled: true,
        position: 'inline_end',
        gap: 12,
        scaleRatio: 1.25,
        animation: 'pop_bounce',
        fallbackEmoji: '😱',
        allowedTaxonomy: ['shock', 'laughter', 'rage', 'crying'],
      },
    },
    // 5. 페페 감정 밈 레이어
    {
      id: 'layer_ssul_pepe_meme',
      name: '페페 리액션 밈',
      kind: 'media',
      mediaRole: 'reaction_meme',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 1380, width: 640, height: 640, rotation: 0, scale: 1, origin: 'center', zIndex: 20 },
      inMs: 0,
      outMs: null,
      opacity: 1,
      assetId: 'pepe_shocked',
      fit: 'contain',
      focus: [0.5, 0.5],
      motion: { type: 'zoom_in', strength: 0.08, durationMs: 2500 },
      clipFromMs: 0,
    },
  ];

  return {
    schemaVersion: 'viraloop-blueprint/v3',
    blueprintId: id,
    name,
    archetype: 'ssul',
    canvas: { width: 1080, height: 1920, fps: '30', backgroundColor: '#0F172A' },
    layers,
    productionDNA: {
      audio: { ttsVolumeDb: -3.0, bgmVolumeDb: -22.0, bgmDuckingDb: -26.0, duckingFadeMs: 350, voiceCadenceWpm: 310, voicePitchF0: 1.0 },
      pacing: { jabHookDurationMs: 800, minCutDurationMs: 1500, maxCutDurationMs: 3500 },
      safeZones: { rightGuardWidth: 120, bottomGuardHeight: 240, topGuardHeight: 180 },
    },
    samplePreview: {
      channelName: '썰보관소',
      title: '회사에서 겪은 역대급 황당 썰',
      lines: [
        { text: '여기에 첫 번째 줄이 들어가요', emotion: 'neutral' },
        { text: '장면마다 줄이 하나씩 쌓여요', emotion: 'shock' },
        { text: '말도 안 되는 충격 반전 실화 😱', emotion: 'shock' },
      ],
      mediaAssets: { sample1: 'sample1.jpg', pepe_shocked: 'pepe_shocked.png' },
    },
  };
}

export function createGunlimboArchetype(id: string = 'archetype_gunlimbo', name: string = '군림보 기본 원형'): VLStandardBlueprint {
  const layers: VLLayerObject[] = [
    // 1. 메인 줌인/줌아웃 비디오
    {
      id: 'layer_gunlimbo_video',
      name: '메인 줌 비디오',
      kind: 'media',
      mediaRole: 'main_background',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 960, width: 1080, height: 1920, rotation: 0, scale: 1, origin: 'center', zIndex: 1 },
      inMs: 0,
      outMs: null,
      opacity: 1,
      assetId: 'sample1',
      fit: 'cover',
      focus: [0.5, 0.5],
      motion: { type: 'zoom_in', strength: 0.12, durationMs: 3000 },
      clipFromMs: 0,
    },
    // 2. 상단 긴급 속보 빨간 배너
    {
      id: 'layer_gunlimbo_news_banner',
      name: '긴급 속보 배너',
      kind: 'shape',
      shapeRole: 'urgent_banner',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 80, width: 1080, height: 90, rotation: 0, scale: 1, origin: 'center', zIndex: 10 },
      inMs: 0,
      outMs: null,
      opacity: 1,
      fillColor: '#DC2626',
      borderRadius: 0,
      borderWidth: 0,
    },
    {
      id: 'layer_gunlimbo_news_text',
      name: '속보 텍스트',
      kind: 'text',
      textRole: 'badge',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 80, width: 900, height: 60, rotation: 0, scale: 1, origin: 'center', zIndex: 11 },
      inMs: 0,
      outMs: null,
      opacity: 1,
      content: '🚨 [긴급 단독 보도] 충격 실체 공개',
      fontFamily: 'NotoSansKR-Bold',
      fontSize: 38,
      fontColor: '#FFFFFF',
      letterSpacing: -1,
      lineHeight: 1.2,
      textAlign: 'center',
      borderRadius: 0,
      padding: [0, 0, 0, 0],
      accumulateMode: false,
    },
    // 3. 상단 화이트 훅 밴드
    {
      id: 'layer_gunlimbo_hook_band',
      name: '화이트 훅 밴드',
      kind: 'shape',
      shapeRole: 'hook_band',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 220, width: 1080, height: 180, rotation: 0, scale: 1, origin: 'center', zIndex: 12 },
      inMs: 0,
      outMs: 3000, // 처음 3초간만 노출
      opacity: 1,
      fillColor: '#FFFFFF',
      borderRadius: 0,
      borderWidth: 0,
    },
    {
      id: 'layer_gunlimbo_hook_text',
      name: '훅 임팩트 문구',
      kind: 'text',
      textRole: 'hook_punch',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 220, width: 980, height: 140, rotation: 0, scale: 1, origin: 'center', zIndex: 13 },
      inMs: 0,
      outMs: 3000,
      opacity: 1,
      content: '끝까지 보면 소름 돋습니다',
      fontFamily: 'NotoSansKR-Bold',
      fontSize: 58,
      fontColor: '#000000',
      letterSpacing: -1.5,
      lineHeight: 1.2,
      textAlign: 'center',
      borderRadius: 0,
      padding: [0, 0, 0, 0],
      accumulateMode: false,
    },
    // 4. 하단 블랙 박스 고대비 자막
    {
      id: 'layer_gunlimbo_sub_bg',
      name: '자막 배경 박스',
      kind: 'shape',
      shapeRole: 'comment_card',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 1540, width: 980, height: 160, rotation: 0, scale: 1, origin: 'center', zIndex: 15 },
      inMs: 0,
      outMs: null,
      opacity: 0.85,
      fillColor: '#000000',
      borderRadius: 20,
      borderWidth: 2,
      borderColor: '#FBBF24',
    },
    {
      id: 'layer_gunlimbo_sub_text',
      name: '군림보 2-Tone 자막',
      kind: 'text',
      textRole: 'subtitle_narrative',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 1540, width: 940, height: 140, rotation: 0, scale: 1, origin: 'center', zIndex: 16 },
      inMs: 0,
      outMs: null,
      opacity: 1,
      content: '자막은 여기에 강조해서 보여요',
      fontFamily: 'NotoSansKR-Bold',
      fontSize: 56,
      fontColor: '#FBBF24',
      letterSpacing: -1,
      lineHeight: 1.3,
      textAlign: 'center',
      borderRadius: 0,
      padding: [0, 0, 0, 0],
      accumulateMode: false,
      emojiSlot: {
        enabled: true,
        position: 'inline_end',
        gap: 14,
        scaleRatio: 1.2,
        animation: 'pop_bounce',
        fallbackEmoji: '🔥',
        allowedTaxonomy: ['shock', 'rage', 'suspense'],
      },
    },
  ];

  return {
    schemaVersion: 'viraloop-blueprint/v3',
    blueprintId: id,
    name,
    archetype: 'gunlimbo',
    canvas: { width: 1080, height: 1920, fps: '30', backgroundColor: '#000000' },
    layers,
    productionDNA: {
      audio: { ttsVolumeDb: -2.5, bgmVolumeDb: -20.0, bgmDuckingDb: -25.0, duckingFadeMs: 300, voiceCadenceWpm: 320, voicePitchF0: 1.05 },
      pacing: { jabHookDurationMs: 800, minCutDurationMs: 1200, maxCutDurationMs: 3000 },
      safeZones: { rightGuardWidth: 120, bottomGuardHeight: 240, topGuardHeight: 180 },
    },
    samplePreview: {
      channelName: '군림보이슈',
      title: '새벽 편의점 알바생의 비밀',
      lines: [
        { text: '끝까지 보면 소름 돋습니다', emotion: 'suspense' },
        { text: '새벽 3시 편의점에 찾아온 의문의 손님', emotion: 'shock' },
      ],
      mediaAssets: { sample1: 'sample1.jpg' },
    },
  };
}

export function createInstagramArchetype(id: string = 'archetype_instagram', name: string = '인스타 카드 기본 원형'): VLStandardBlueprint {
  const layers: VLLayerObject[] = [
    // 1. 배경 블러 비디오
    {
      id: 'layer_insta_bg',
      name: '인스타 배경 미디어',
      kind: 'media',
      mediaRole: 'main_background',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 960, width: 1080, height: 1920, rotation: 0, scale: 1, origin: 'center', zIndex: 1 },
      inMs: 0,
      outMs: null,
      opacity: 1,
      assetId: 'sample1',
      fit: 'cover',
      focus: [0.5, 0.5],
      motion: { type: 'pan_left', strength: 0.05, durationMs: 4000 },
      clipFromMs: 0,
    },
    // 2. 중앙 반투명 인스타 카드
    {
      id: 'layer_insta_card_bg',
      name: '반투명 댓글 카드',
      kind: 'shape',
      shapeRole: 'comment_card',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 960, width: 980, height: 680, rotation: 0, scale: 1, origin: 'center', zIndex: 10 },
      inMs: 0,
      outMs: null,
      opacity: 0.9,
      fillColor: 'rgba(20, 24, 39, 0.85)',
      borderRadius: 36,
      borderWidth: 1.5,
      borderColor: 'rgba(255, 255, 255, 0.15)',
    },
    // 3. 프로필 계정 텍스트
    {
      id: 'layer_insta_profile_text',
      name: '프로필 계정명',
      kind: 'text',
      textRole: 'badge',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 720, width: 880, height: 60, rotation: 0, scale: 1, origin: 'center', zIndex: 12 },
      inMs: 0,
      outMs: null,
      opacity: 1,
      content: '@viraloop_creator · 인증됨 ✓',
      fontFamily: 'NotoSansKR-Bold',
      fontSize: 36,
      fontColor: '#38BDF8',
      letterSpacing: -0.5,
      lineHeight: 1.2,
      textAlign: 'left',
      borderRadius: 0,
      padding: [0, 0, 0, 0],
      accumulateMode: false,
    },
    // 4. 본문 댓글 내용
    {
      id: 'layer_insta_content_text',
      name: '카드 본문 텍스트',
      kind: 'text',
      textRole: 'subtitle_narrative',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 960, width: 880, height: 380, rotation: 0, scale: 1, origin: 'center', zIndex: 14 },
      inMs: 0,
      outMs: null,
      opacity: 1,
      content: '주말에 다녀온 바닷가 카페 이야기\n창가 자리에 앉으면 바다가 한눈에 보여요',
      fontFamily: 'NotoSansKR-Bold',
      fontSize: 48,
      fontColor: '#F8FAFC',
      letterSpacing: -1,
      lineHeight: 1.45,
      textAlign: 'left',
      borderRadius: 0,
      padding: [0, 0, 0, 0],
      accumulateMode: false,
      emojiSlot: {
        enabled: true,
        position: 'inline_end',
        gap: 12,
        scaleRatio: 1.2,
        animation: 'pop_bounce',
        fallbackEmoji: '✨',
        allowedTaxonomy: ['laughter', 'crying', 'shock'],
      },
    },
  ];

  return {
    schemaVersion: 'viraloop-blueprint/v3',
    blueprintId: id,
    name,
    archetype: 'instagram',
    canvas: { width: 1080, height: 1920, fps: '30', backgroundColor: '#090D16' },
    layers,
    productionDNA: {
      audio: { ttsVolumeDb: -3.0, bgmVolumeDb: -22.0, bgmDuckingDb: -26.0, duckingFadeMs: 350, voiceCadenceWpm: 300, voicePitchF0: 1.0 },
      pacing: { jabHookDurationMs: 800, minCutDurationMs: 1500, maxCutDurationMs: 3500 },
      safeZones: { rightGuardWidth: 120, bottomGuardHeight: 280, topGuardHeight: 180 },
    },
    samplePreview: {
      channelName: '인스타트렌드',
      title: '주말 바닷가 카페 이야기',
      lines: [
        { text: '창가 자리에 앉으면 바다가 한눈에 보여요', emotion: 'neutral' },
        { text: '해질녘에는 하늘이 분홍빛으로 물들어요', emotion: 'neutral' },
      ],
      mediaAssets: { sample1: 'sample1.jpg' },
    },
  };
}

export function createClassicArchetype(id: string = 'archetype_classic', name: string = '클래식 바이럴 기본 원형'): VLStandardBlueprint {
  const layers: VLLayerObject[] = [
    // 1. 메인 9:16 비디오
    {
      id: 'layer_classic_video',
      name: '메인 비디오',
      kind: 'media',
      mediaRole: 'main_background',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 960, width: 1080, height: 1920, rotation: 0, scale: 1, origin: 'center', zIndex: 1 },
      inMs: 0,
      outMs: null,
      opacity: 1,
      assetId: 'sample1',
      fit: 'cover',
      focus: [0.5, 0.5],
      motion: { type: 'none', strength: 0.1, durationMs: 3000 },
      clipFromMs: 0,
    },
    // 2. 상단 볼드 타이틀 헤더
    {
      id: 'layer_classic_header',
      name: '상단 타이틀 헤더',
      kind: 'text',
      textRole: 'title_header',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 220, width: 980, height: 140, rotation: 0, scale: 1, origin: 'center', zIndex: 10 },
      inMs: 0,
      outMs: null,
      opacity: 1,
      content: '0.8초 쨉쨉이 충격 반전 실화',
      fontFamily: 'NotoSansKR-Bold',
      fontSize: 54,
      fontColor: '#FFE600',
      letterSpacing: -1.5,
      lineHeight: 1.25,
      textAlign: 'center',
      stroke: { color: '#000000', width: 8 },
      shadow: { color: 'rgba(0,0,0,0.9)', blur: 16, offsetX: 0, offsetY: 6 },
      borderRadius: 0,
      padding: [0, 0, 0, 0],
      accumulateMode: false,
    },
    // 3. 중앙 바이럴 자막
    {
      id: 'layer_classic_sub',
      name: '중앙 바이럴 자막',
      kind: 'text',
      textRole: 'subtitle_narrative',
      locked: false,
      hidden: false,
      transform: { x: 540, y: 1420, width: 980, height: 180, rotation: 0, scale: 1, origin: 'center', zIndex: 12 },
      inMs: 0,
      outMs: null,
      opacity: 1,
      content: '여기에 대사가 한 줄씩 표시됩니다',
      fontFamily: 'NotoSansKR-Bold',
      fontSize: 58,
      fontColor: '#FFFFFF',
      letterSpacing: -1,
      lineHeight: 1.3,
      textAlign: 'center',
      stroke: { color: '#000000', width: 8 },
      shadow: { color: 'rgba(0,0,0,0.85)', blur: 14, offsetX: 0, offsetY: 5 },
      borderRadius: 0,
      padding: [0, 0, 0, 0],
      accumulateMode: false,
      emojiSlot: {
        enabled: true,
        position: 'inline_end',
        gap: 14,
        scaleRatio: 1.2,
        animation: 'pop_bounce',
        fallbackEmoji: '🔥',
        allowedTaxonomy: ['shock', 'rage', 'laughter'],
      },
    },
  ];

  return {
    schemaVersion: 'viraloop-blueprint/v3',
    blueprintId: id,
    name,
    archetype: 'classic',
    canvas: { width: 1080, height: 1920, fps: '30', backgroundColor: '#000000' },
    layers,
    productionDNA: {
      audio: { ttsVolumeDb: -3.0, bgmVolumeDb: -22.0, bgmDuckingDb: -26.0, duckingFadeMs: 350, voiceCadenceWpm: 310, voicePitchF0: 1.0 },
      pacing: { jabHookDurationMs: 800, minCutDurationMs: 1500, maxCutDurationMs: 3500 },
      safeZones: { rightGuardWidth: 120, bottomGuardHeight: 240, topGuardHeight: 180 },
    },
    samplePreview: {
      channelName: '클래식쇼츠',
      title: '0.8초 쨉쨉이 충격 반전',
      lines: [
        { text: '여기에 대사가 한 줄씩 표시됩니다', emotion: 'neutral' },
        { text: '끝까지 시청해야 알 수 있는 진실', emotion: 'shock' },
      ],
      mediaAssets: { sample1: 'sample1.jpg' },
    },
  };
}

export function getArchetypePreset(archetype: 'ssul' | 'gunlimbo' | 'instagram' | 'classic' | 'bespoke', id?: string, name?: string): VLStandardBlueprint {
  switch (archetype) {
    case 'ssul':
      return createSsulArchetype(id, name);
    case 'gunlimbo':
      return createGunlimboArchetype(id, name);
    case 'instagram':
      return createInstagramArchetype(id, name);
    case 'classic':
    default:
      return createClassicArchetype(id, name);
  }
}
