import json, base64, sqlite3, os, shutil
from pathlib import Path
import win32crypt
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

def sync_browser_cookies():
    local_app = Path(os.environ.get('LOCALAPPDATA', ''))
    profile_dir = local_app / 'ViraLoop Studio' / 'media' / '04_Profiles' / 'browser_user_data'
    local_state_path = profile_dir / 'Local State'
    if not local_state_path.exists():
        print("No Local State found")
        return []
    
    with open(local_state_path, 'r', encoding='utf-8') as f:
        ls = json.load(f)

    enc_key = base64.b64decode(ls['os_crypt']['encrypted_key'])[5:]
    aes_key = win32crypt.CryptUnprotectData(enc_key, None, None, None, 0)[1]
    aesgcm = AESGCM(aes_key)

    db_path = profile_dir / 'Default' / 'Network' / 'Cookies'
    if not db_path.exists():
        print("No Cookies db found")
        return []

    temp_db = profile_dir / 'Default' / 'Network' / 'Cookies_extract_sync'
    try:
        shutil.copy2(db_path, temp_db)
    except Exception as e:
        print(f"Failed to copy cookies db: {e}")
        return []

    conn = sqlite3.connect(temp_db)
    cursor = conn.cursor()
    cursor.execute("SELECT host_key, name, encrypted_value, path, is_secure, is_httponly, expires_utc FROM cookies")
    rows = cursor.fetchall()
    
    results = []
    for host, name, enc_val, path, is_sec, is_http, exp in rows:
        val = ""
        if enc_val.startswith(b'v10'):
            nonce = enc_val[3:15]
            ciphertext = enc_val[15:]
            try:
                raw = aesgcm.decrypt(nonce, ciphertext, None)
                if len(raw) > 32:
                    val = raw[32:].decode('utf-8', errors='ignore')
                else:
                    val = raw.decode('utf-8', errors='ignore')
            except Exception:
                continue
        elif enc_val:
            try:
                val = win32crypt.CryptUnprotectData(enc_val, None, None, None, 0)[1].decode('utf-8', errors='ignore')
            except Exception:
                continue

        if val:
            exp_unix = (exp // 1000000) - 11644473600 if exp > 0 else 0
            # Construct standard cookie URL for Electron session.cookies.set
            clean_host = host.lstrip('.')
            results.append({
                "domain": host,
                "name": name,
                "value": val,
                "path": path,
                "secure": bool(is_sec),
                "httpOnly": bool(is_http),
                "expirationDate": exp_unix if exp_unix > 0 else None,
                "url": f"https://{clean_host}{path}"
            })

    conn.close()
    temp_db.unlink(missing_ok=True)

    out_file = profile_dir / 'extracted_cookies.json'
    with open(out_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2)
    print(f"Saved {len(results)} cookies to {out_file}")

    # Also save cookies_gemini.json and cookies_gemini.txt for kellybk1000@gmail.com
    gweb_dir = local_app / 'ViraLoop Studio' / 'media' / '04_Profiles' / 'gemini_web'
    gweb_dir.mkdir(parents=True, exist_ok=True)
    google_cookies = [c for c in results if 'google' in c['domain']]
    sec1psid = next((c['value'] for c in google_cookies if c['name'] == '__Secure-1PSID'), None)
    
    gemini_payload = {
        "email": "kellybk1000@gmail.com",
        "secure_1psid": sec1psid,
        "updated_at": "2026-09-29T22:30:00Z",
        "cookie_count": len(google_cookies),
        "cookies": google_cookies
    }
    with open(gweb_dir / 'cookies_gemini.json', 'w', encoding='utf-8') as f:
        json.dump(gemini_payload, f, indent=2)

    lines = ["# Netscape HTTP Cookie File", "# Generated by ViraLoop Sync", ""]
    for c in google_cookies:
        dom = c.get("domain", "")
        sub = "TRUE" if dom.startswith(".") else "FALSE"
        path_val = c.get("path", "/")
        sec = "TRUE" if c.get("secure") else "FALSE"
        exp = int(c.get("expirationDate") or 0)
        lines.append(f"{dom}\t{sub}\t{path_val}\t{sec}\t{exp}\t{c.get('name', '')}\t{c.get('value', '')}")
    with open(gweb_dir / 'cookies_gemini.txt', 'w', encoding='utf-8') as f:
        f.write("\n".join(lines) + "\n")
    print(f"Saved cookies_gemini to {gweb_dir}")

    # Also copy to google_accounts/kellybk1000@gmail.com
    acc_dir = local_app / 'ViraLoop Studio' / 'media' / '04_Profiles' / 'google_accounts' / 'kellybk1000@gmail.com'
    acc_dir.mkdir(parents=True, exist_ok=True)
    with open(acc_dir / 'cookies_gemini.json', 'w', encoding='utf-8') as f:
        json.dump(gemini_payload, f, indent=2)
    with open(acc_dir / 'cookies_gemini.txt', 'w', encoding='utf-8') as f:
        f.write("\n".join(lines) + "\n")
    print(f"Saved to account pool: {acc_dir}")

    return results

if __name__ == '__main__':
    sync_browser_cookies()
