/**
 * Electron IPC Handler - Google Gemini Web Session & Cookie Vault (Tier 3)
 *
 * Provides native stealth browser window for gemini.google.com authentication.
 * Automatically intercepts and captures session cookies:
 *   - __Secure-1PSID
 *   - __Secure-1PSIDTS
 *   - __Secure-1PSIDCC
 *   - SID, HSID, SSID, SAPISID
 *
 * Saves cookies in both Netscape format (cookies_gemini.txt) and JSON (cookies_gemini.json)
 * into %LOCALAPPDATA%\ViraLoop Studio\media\04_Profiles\gemini_web\.
 */

import { app, BrowserWindow, session, clipboard } from 'electron'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import fs from 'node:fs/promises'
import fsSync from 'node:fs'
import os from 'node:os'
import http from 'node:http'
import { loadProfiles, updateProfile, createProfile } from '../profileManager.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

function getLoginPreloadPath() {
  const candidates = [
    path.resolve(__dirname, 'login_preload.mjs'),
    path.resolve(__dirname, 'login_preload.js'),
    path.resolve(__dirname, '..', 'login_preload.js'),
    path.resolve(__dirname, '../electron/login_preload.js'),
    path.resolve(__dirname, '../dist-electron/login_preload.mjs')
  ]
  try {
    if (app && typeof app.getAppPath === 'function') {
      candidates.push(path.join(app.getAppPath(), 'dist-electron', 'login_preload.mjs'))
      candidates.push(path.join(app.getAppPath(), 'electron', 'login_preload.js'))
    }
  } catch {}
  for (const c of candidates) {
    if (fsSync.existsSync(c)) return c
  }
  return undefined
}

const GEMINI_WEB_URL = 'https://gemini.google.com'
const PARTITION_NAME = 'persist:gemini_web'

function getGeminiWebDir() {
  const localAppData = process.env.LOCALAPPDATA || path.join(os.homedir(), 'AppData', 'Local')
  const dir = path.join(localAppData, 'ViraLoop Studio', 'media', '04_Profiles', 'gemini_web')
  try {
    fsSync.mkdirSync(dir, { recursive: true })
  } catch (e) {}
  return dir
}

function getAntigravitySessionDir(email) {
  const localAppData = process.env.LOCALAPPDATA || path.join(os.homedir(), 'AppData', 'Local')
  const sanitized = (email || 'unknown').replace(/[^a-zA-Z0-9.@_-]/g, '_')
  const dir = path.join(localAppData, 'ViraLoop Studio', 'media', '04_Profiles', 'antigravity_sessions', sanitized)
  try {
    fsSync.mkdirSync(dir, { recursive: true })
  } catch (e) {}
  return dir
}

function cookiesToNetscape(cookies) {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by ViraLoop Studio for Google Gemini Web',
    '# Created at ' + new Date().toISOString(),
    ''
  ]

  for (const c of cookies) {
    const domain = c.domain || ''
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const pathVal = c.path || '/'
    const secure = c.secure ? 'TRUE' : 'FALSE'
    let expiration = Math.floor(c.expirationDate || 0)
    if (expiration <= 0) {
      expiration = Math.floor(Date.now() / 1000) + 86400 * 365
    }
    lines.push([domain, includeSubdomains, pathVal, secure, expiration, c.name, c.value].join('\t'))
  }
  return lines.join('\n') + '\n'
}

async function notifyBackendSession(sessionData) {
  return new Promise((resolve) => {
    try {
      const payload = JSON.stringify(sessionData)
      const req = http.request(
        {
          hostname: '127.0.0.1',
          port: 8000,
          path: '/api/ai-accounts/gemini/web-session',
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Content-Length': Buffer.byteLength(payload)
          }
        },
        (res) => {
          resolve(res.statusCode === 200)
        }
      )
      req.on('error', () => resolve(false))
      req.write(payload)
      req.end()
    } catch {
      resolve(false)
    }
  })
}

async function notifyBackendAccountKey(email, key) {
  return new Promise((resolve) => {
    try {
      const payload = JSON.stringify({ email, key })
      const req = http.request(
        {
          hostname: '127.0.0.1',
          port: 8000,
          path: '/api/ai-accounts/gemini/account-key',
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Content-Length': Buffer.byteLength(payload)
          }
        },
        (res) => {
          resolve(res.statusCode === 200)
        }
      )
      req.on('error', () => resolve(false))
      req.write(payload)
      req.end()
    } catch {
      resolve(false)
    }
  })
}

async function notifyBackendAntigravityCode(email, code) {
  return new Promise((resolve) => {
    try {
      const payload = JSON.stringify({ email, code })
      const req = http.request(
        {
          hostname: '127.0.0.1',
          port: 8000,
          path: '/api/ai-accounts/gemini/exchange-antigravity-code',
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Content-Length': Buffer.byteLength(payload)
          }
        },
        (res) => {
          let body = ''
          res.on('data', (chunk) => {
            body += chunk
          })
          res.on('end', () => {
            try {
              resolve(JSON.parse(body))
            } catch {
              resolve({ success: res.statusCode === 200 })
            }
          })
        }
      )
      req.on('error', (err) => resolve({ success: false, error: err.message }))
      req.write(payload)
      req.end()
    } catch (e) {
      resolve({ success: false, error: e.message })
    }
  })
}

async function resolvePartitionForTarget(emailOrProfileId) {
  try {
    const config = await loadProfiles()
    if (config && config.profiles) {
      // 1. Exact match by Flow profile ID or Email (Unifying Google Flow and Gemini AI accounts!)
      let matched = config.profiles.find(
        (p) =>
          p.id === emailOrProfileId ||
          (p.email &&
            emailOrProfileId &&
            p.email.toLowerCase().trim() === emailOrProfileId.toLowerCase().trim())
      )
      if (matched) {
        return {
          partition:
            matched.id === 'default'
              ? 'persist:flow_profile_default'
              : `persist:flow_profile_${matched.id}`,
          profile: matched,
          isFlowProfile: true
        }
      }
    }
  } catch (err) {
    console.warn('[Gemini Web IPC] resolvePartitionForTarget error:', err)
  }

  // 2. If it's a new email not yet in Flow profiles, auto-register as a new Flow profile for unified management!
  if (emailOrProfileId && emailOrProfileId.includes('@')) {
    try {
      const created = await createProfile(emailOrProfileId.split('@')[0], emailOrProfileId.trim())
      if (created && created.success && created.profile) {
        return {
          partition:
            created.profile.id === 'default'
              ? 'persist:flow_profile_default'
              : `persist:flow_profile_${created.profile.id}`,
          profile: created.profile,
          isFlowProfile: true
        }
      }
    } catch (e) {
      console.warn('[Gemini Web IPC] Auto-create flow profile failed:', e)
    }

    const cleanKey = emailOrProfileId.trim().toLowerCase().replace(/[^a-z0-9]/g, '_')
    return {
      partition: `persist:flow_profile_${cleanKey}`,
      profile: { id: cleanKey, name: emailOrProfileId, email: emailOrProfileId },
      isFlowProfile: true
    }
  }

  // 3. Fallback: only when no email and no profile ID was given (default flow profile)
  return { partition: 'persist:flow_profile_default', profile: null, isFlowProfile: true }
}

export function registerGeminiWebIPC(ipcMain) {
  // 1. Open interactive stealth login window for Gemini Web
  ipcMain.handle('gemini:open-web-login', async (_event, emailHint) => {
    const { partition, profile } = await resolvePartitionForTarget(emailHint)
    const customSession = session.fromPartition(partition)

    // WebAuthn Passkey modal 방지 (Windows 보안 창 방지)
    customSession.setPermissionRequestHandler((webContents, permission, callback) => {
      if (['security-key', 'u2f', 'webauthn'].includes(permission)) {
        return callback(false)
      }
      callback(true)
    })

    const modernChromeUA =
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'
    customSession.setUserAgent(modernChromeUA)

    // Anti-bot header correction for Google Accounts
    customSession.webRequest.onBeforeSendHeaders(
      { urls: ['https://accounts.google.com/*', 'https://*.google.com/*', 'https://gemini.google.com/*'] },
      (details, callback) => {
        const headers = { ...details.requestHeaders }
        headers['User-Agent'] = modernChromeUA
        headers['Sec-Ch-Ua'] = '"Chromium";v="136", "Google Chrome";v="136", "Not-A.Brand";v="99"'
        headers['Sec-Ch-Ua-Mobile'] = '?0'
        headers['Sec-Ch-Ua-Platform'] = '"Windows"'
        callback({ cancel: false, requestHeaders: headers })
      }
    )

    // [A] 미디어 일괄 생성(Flow) 세션에 이미 로그인된 구글 쿠키가 있는지 먼저 즉시 확인
    try {
      const existingCookies = await customSession.cookies.get({})
      const existing1psid = existingCookies.find((c) => c.name === '__Secure-1PSID')

      // 세션 오염 방지: 쿠키 내 실제 이메일과 요청된 이메일이 다르면 가져오지 않음
      let emailMatches = true
      const emailCookie = existingCookies.find((c) => c.name === 'EMAIL')
      if (emailCookie && emailCookie.value && emailHint && emailHint.includes('@')) {
        const decoded = decodeURIComponent(emailCookie.value).replace(/["']/g, '').trim().toLowerCase()
        if (decoded && decoded !== emailHint.trim().toLowerCase()) {
          console.warn(`[Gemini Web IPC] Cookie email mismatch: expected ${emailHint}, found ${decoded}. Ignoring old session!`)
          emailMatches = false
        }
      }

      if (existing1psid && emailMatches) {
        console.log(`[Gemini Web IPC] Found existing __Secure-1PSID in partition '${partition}'. Instant sync!`)
        const finalEmail = profile?.email || emailHint || 'gemini_user@gmail.com'
        const targetDir = getGeminiWebDir()
        const txtPath = path.join(targetDir, 'cookies_gemini.txt')
        const jsonPath = path.join(targetDir, 'cookies_gemini.json')

        const sessionData = {
          email: finalEmail,
          secure_1psid: existing1psid.value,
          updated_at: new Date().toISOString(),
          cookie_count: existingCookies.length,
          cookies: existingCookies.map((c) => ({
            name: c.name,
            value: c.value,
            domain: c.domain,
            path: c.path,
            secure: c.secure,
            httpOnly: c.httpOnly,
            expirationDate: c.expirationDate
          }))
        }

        await fs.writeFile(jsonPath, JSON.stringify(sessionData, null, 2), 'utf-8')
        await fs.writeFile(txtPath, cookiesToNetscape(existingCookies), 'utf-8')

        if (finalEmail && finalEmail.includes('@') && finalEmail !== 'gemini_user@gmail.com') {
          const accDir = getAntigravitySessionDir(finalEmail)
          await fs.writeFile(path.join(accDir, 'cookies_gemini.json'), JSON.stringify(sessionData, null, 2), 'utf-8')
          await fs.writeFile(path.join(accDir, 'cookies_gemini.txt'), cookiesToNetscape(existingCookies), 'utf-8')
          const meta = {
            account_id: finalEmail,
            email: finalEmail,
            tier: 'Google AI Pro (Antigravity + Web 통합)',
            linked_at: new Date().toISOString(),
            has_web_cookies: true,
            cookie_count: existingCookies.length,
            profile_dir: accDir
          }
          await fs.writeFile(path.join(accDir, 'session_metadata.json'), JSON.stringify(meta, null, 2), 'utf-8')
        }

        await notifyBackendSession(sessionData)

        return {
          success: true,
          email: finalEmail,
          secure1psid: existing1psid.value,
          cookieCount: existingCookies.length,
          alreadyLoggedIn: true,
          message: `[${profile?.name || finalEmail}] 미디어 일괄 생성(Flow) 세션에서 Google 쿠키가 즉시 연동되었습니다!`
        }
      }
    } catch (e) {
      console.warn('[Gemini Web IPC] Existing cookie check error:', e)
    }

    // [B] 아직 쿠키가 없는 경우 순정 크롬 호환 독립 세션 브라우저 창 실행
    let preloadPath = path.join(__dirname, 'login_preload.js')
    if (!fsSync.existsSync(preloadPath)) {
      preloadPath = path.join(__dirname, 'login_preload.mjs')
    }
    if (!fsSync.existsSync(preloadPath)) {
      preloadPath = path.join(app.getAppPath(), 'electron', 'login_preload.js')
    }
    if (!fsSync.existsSync(preloadPath)) {
      preloadPath = path.join(__dirname, '../electron/login_preload.js')
    }

    const win = new BrowserWindow({
      width: 1050,
      height: 780,
      title: `Google 계정 통합 로그인 (${profile?.name ? profile.name + ' - ' : ''}Tier 1 Antigravity & Tier 3 Gemini Web 동시 연동)`,
      autoHideMenuBar: true,
      webPreferences: {
        session: customSession,
        preload: fsSync.existsSync(preloadPath) ? preloadPath : undefined,
        nodeIntegration: false,
        contextIsolation: true,
        plugins: true,
        webSecurity: true
      }
    })

    win.webContents.setUserAgent(modernChromeUA)

    win.webContents.setWindowOpenHandler(({ url }) => {
      return { action: 'allow' }
    })

    // Natural navigation with AccountChooser for target email
    const targetEmail = emailHint && emailHint.includes('@') ? emailHint.trim() : (profile?.email || null)
    let targetUrl = GEMINI_WEB_URL
    if (targetEmail) {
      targetUrl = `https://accounts.google.com/AccountChooser?Email=${encodeURIComponent(targetEmail)}&continue=${encodeURIComponent(GEMINI_WEB_URL)}`
    }
    win.loadURL(targetUrl)

    return new Promise((resolve) => {
      let pollInterval = null
      let captured = false

      const checkCookies = async () => {
        if (captured || win.isDestroyed()) return

        try {
          const currentUrl = win.webContents.getURL() || ''
          const cookies = await customSession.cookies.get({})
          const secure1psid = cookies.find((c) => c.name === '__Secure-1PSID')

          // Gemini domain entered and __Secure-1PSID acquired
          if (secure1psid && (currentUrl.includes('gemini.google.com') || currentUrl.includes('google.com/gemini'))) {
            captured = true
            clearInterval(pollInterval)

            let capturedEmail = emailHint || null
            try {
              const domEmail = await win.webContents.executeJavaScript(`
                (() => {
                  try {
                    // 1. Profile avatar / button with aria-label containing email
                    const ariaEls = document.querySelectorAll('[aria-label*="@"]');
                    for (const el of ariaEls) {
                      const m = (el.getAttribute('aria-label') || '').match(/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}/);
                      if (m) return m[0];
                    }
                    // 2. Data attributes
                    const dataEls = document.querySelectorAll('[data-identifier], [data-email]');
                    for (const el of dataEls) {
                      const val = el.getAttribute('data-identifier') || el.getAttribute('data-email') || '';
                      const m = val.match(/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}/);
                      if (m) return m[0];
                    }
                    // 3. Anchors with google account links
                    const links = document.querySelectorAll('a[href*="accounts.google.com"], button');
                    for (const el of links) {
                      const m = (el.textContent || '').match(/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}/);
                      if (m) return m[0];
                    }
                    // 4. Any email on page
                    const bodyMatches = (document.body?.innerText || '').match(/[a-zA-Z0-9._%+-]+@(gmail\\.com|[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,})/);
                    if (bodyMatches) return bodyMatches[0];
                    return null;
                  } catch (e) {
                    return null;
                  }
                })()
              `)
              if (domEmail) capturedEmail = domEmail
            } catch {}

            const finalEmail = capturedEmail || 'gemini_user@gmail.com'
            const targetDir = getGeminiWebDir()
            const txtPath = path.join(targetDir, 'cookies_gemini.txt')
            const jsonPath = path.join(targetDir, 'cookies_gemini.json')

            const sessionData = {
              email: finalEmail,
              secure_1psid: secure1psid.value,
              updated_at: new Date().toISOString(),
              cookie_count: cookies.length,
              cookies: cookies.map((c) => ({
                name: c.name,
                value: c.value,
                domain: c.domain,
                path: c.path,
                secure: c.secure,
                httpOnly: c.httpOnly,
                expirationDate: c.expirationDate
              }))
            }

            // Write to active 04_Profiles/gemini_web
            await fs.writeFile(jsonPath, JSON.stringify(sessionData, null, 2), 'utf-8')
            await fs.writeFile(txtPath, cookiesToNetscape(cookies), 'utf-8')

            // Write to dedicated independent account profile folder
            if (finalEmail && finalEmail.includes('@') && finalEmail !== 'gemini_user@gmail.com') {
              const accDir = getAntigravitySessionDir(finalEmail)
              await fs.writeFile(path.join(accDir, 'cookies_gemini.json'), JSON.stringify(sessionData, null, 2), 'utf-8')
              await fs.writeFile(path.join(accDir, 'cookies_gemini.txt'), cookiesToNetscape(cookies), 'utf-8')
              const meta = {
                account_id: finalEmail,
                email: finalEmail,
                tier: 'Google AI Pro (Antigravity + Web 통합)',
                linked_at: new Date().toISOString(),
                has_web_cookies: true,
                cookie_count: cookies.length,
                profile_dir: accDir
              }
              await fs.writeFile(path.join(accDir, 'session_metadata.json'), JSON.stringify(meta, null, 2), 'utf-8')
            }

            if (profile?.id && finalEmail && finalEmail.includes('@')) {
              try {
                await updateProfile(profile.id, profile.name || finalEmail, finalEmail)
              } catch (e) {}
            }

            await notifyBackendSession(sessionData)

            setTimeout(() => {
              if (!win.isDestroyed()) {
                win.close()
              }
            }, 1200)

            resolve({
              success: true,
              email: finalEmail,
              secure1psid: secure1psid.value,
              cookieCount: cookies.length,
              message: `Google 계정(${finalEmail}) 연동 완료! 독립 프로필 생성 및 Antigravity + Web 동시 연동 성공.`
            })
          }
        } catch (err) {
          console.error('[Gemini Web IPC] Cookie check error:', err)
        }
      }

      pollInterval = setInterval(checkCookies, 1500)

      win.webContents.on('did-navigate', () => checkCookies())
      win.webContents.on('did-frame-finish-load', () => checkCookies())

      win.on('closed', async () => {
        if (pollInterval) clearInterval(pollInterval)
        if (!captured) {
          // Check one last time upon close
          try {
            const cookies = await customSession.cookies.get({})
            const secure1psid = cookies.find((c) => c.name === '__Secure-1PSID')
            if (secure1psid) {
              const finalEmail = emailHint || 'gemini_user@gmail.com'
              const targetDir = getGeminiWebDir()
              const txtPath = path.join(targetDir, 'cookies_gemini.txt')
              const jsonPath = path.join(targetDir, 'cookies_gemini.json')
              const sessionData = {
                email: finalEmail,
                secure_1psid: secure1psid.value,
                updated_at: new Date().toISOString(),
                cookie_count: cookies.length,
                cookies: cookies.map((c) => ({
                  name: c.name,
                  value: c.value,
                  domain: c.domain,
                  path: c.path,
                  secure: c.secure,
                  httpOnly: c.httpOnly,
                  expirationDate: c.expirationDate
                }))
              }
              await fs.writeFile(jsonPath, JSON.stringify(sessionData, null, 2), 'utf-8')
              await fs.writeFile(txtPath, cookiesToNetscape(cookies), 'utf-8')

              if (finalEmail && finalEmail.includes('@') && finalEmail !== 'gemini_user@gmail.com') {
                const accDir = getAntigravitySessionDir(finalEmail)
                await fs.writeFile(path.join(accDir, 'cookies_gemini.json'), JSON.stringify(sessionData, null, 2), 'utf-8')
                await fs.writeFile(path.join(accDir, 'cookies_gemini.txt'), cookiesToNetscape(cookies), 'utf-8')
              }

              await notifyBackendSession(sessionData)

              resolve({
                success: true,
                email: finalEmail,
                secure1psid: secure1psid.value,
                cookieCount: cookies.length,
                message: `Google 계정(${finalEmail}) 연동 완료! 독립 프로필 생성 및 Antigravity + Web 동시 연동 성공.`
              })
              return
            }
          } catch {}

          resolve({
            success: false,
            message: '로그인이 완료되기 전에 창이 닫혔습니다.'
          })
        }
      })
    })
  })

  // 1.5. Open Antigravity Dedicated OAuth window with loopback intercept
  ipcMain.handle('gemini:open-antigravity-oauth', async (_event, emailHint) => {
    const { partition, profile } = await resolvePartitionForTarget(emailHint)
    const customSession = session.fromPartition(partition)

    // Anti-bot & WebAuthn modal prevention
    customSession.setPermissionRequestHandler((webContents, permission, callback) => {
      if (['security-key', 'u2f', 'webauthn'].includes(permission)) {
        return callback(false)
      }
      callback(true)
    })

    const modernChromeUA =
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'
    customSession.setUserAgent(modernChromeUA)

    if (!customSession._headersHooked) {
      customSession._headersHooked = true
      customSession.webRequest.onBeforeSendHeaders(
        { urls: ['https://accounts.google.com/*', 'https://*.google.com/*'] },
        (details, callback) => {
          const headers = { ...details.requestHeaders }
          headers['User-Agent'] = modernChromeUA
          headers['Sec-Ch-Ua'] = '"Chromium";v="136", "Google Chrome";v="136", "Not-A.Brand";v="99"'
          headers['Sec-Ch-Ua-Mobile'] = '?0'
          headers['Sec-Ch-Ua-Platform'] = '"Windows"'
          callback({ cancel: false, requestHeaders: headers })
        }
      )
    }

    const targetEmail = (emailHint && emailHint.includes('@')) ? emailHint.trim() : (profile?.email || null)

    const clientId = '1071006060591-tmhssin2h21lcre235vtolojh4g403ep.apps.googleusercontent.com'
    const redirectUri = 'http://localhost:4000/oauth2callback'
    const scope = encodeURIComponent('openid email profile https://www.googleapis.com/auth/cloud-platform')
    let authUrl = `https://accounts.google.com/o/oauth2/v2/auth?client_id=${clientId}&redirect_uri=${encodeURIComponent(redirectUri)}&response_type=code&scope=${scope}&access_type=offline&prompt=consent`
    if (targetEmail) {
      authUrl += `&login_hint=${encodeURIComponent(targetEmail)}&state=${encodeURIComponent(targetEmail)}`
    }

    const preloadPath = getLoginPreloadPath()

    const win = new BrowserWindow({
      width: 900,
      height: 750,
      title: `Google Antigravity OAuth 전용 인증 (${targetEmail || 'Google 계정'})`,
      autoHideMenuBar: true,
      webPreferences: {
        session: customSession,
        preload: preloadPath,
        nodeIntegration: false,
        contextIsolation: true,
        plugins: true,
        webSecurity: true
      }
    })

    win.webContents.setUserAgent(modernChromeUA)

    return new Promise((resolve) => {
      let resolved = false

      // Intercept the redirect to localhost:4000/oauth2callback
      const interceptFilter = { urls: ['http://localhost:4000/oauth2callback*'] }
      customSession.webRequest.onBeforeRequest(interceptFilter, async (details, callback) => {
        try {
          const u = new URL(details.url)
          const code = u.searchParams.get('code')
          const err = u.searchParams.get('error')
          if (code && !resolved) {
            resolved = true
            if (autoApproveTimer) clearInterval(autoApproveTimer)
            const res = await notifyBackendAntigravityCode(targetEmail, code)
            const resultData = res?.result || res || {}
            setTimeout(() => {
              if (!win.isDestroyed()) win.close()
            }, 1000)
            resolve({
              success: true,
              email: resultData.email || targetEmail,
              quotas: resultData.quotas,
              message: resultData.message || 'Antigravity 독립 세션 연동 성공!'
            })
          } else if (err && !resolved) {
            resolved = true
            if (autoApproveTimer) clearInterval(autoApproveTimer)
            resolve({ success: false, message: `OAuth 오류: ${err}` })
          }
        } catch (e) {
          console.warn('[Antigravity OAuth IPC] Intercept error:', e)
        }
        callback({ cancel: true })
      })

      // Auto-approve script: clicks "로그인", "허용", "계속", checkboxes, etc.
      let autoApproveTimer = null
      const tryAutoApprove = async () => {
        if (resolved || win.isDestroyed()) return
        try {
          await win.webContents.executeJavaScript(`
            (() => {
              try {
                // 0. If password field is present, NEVER auto-click anything! Let the user type password!
                const pwdField = document.querySelector('input[type="password"]');
                if (pwdField) {
                  return false;
                }

                // 1. If any unchecked permission checkboxes are present on consent page, check them
                const checkboxes = document.querySelectorAll('input[type="checkbox"]:not(:checked)');
                for (const cb of checkboxes) {
                  cb.click();
                }

                // 2. Click OAuth consent action buttons ONLY (계속, 허용, 동의). Do NOT click "다음" or "Next"!
                const targets = ['계속', '허용', '동의', '동의 및 계속', 'continue', 'allow', 'accept'];
                const candidates = Array.from(document.querySelectorAll('button, div[role="button"], a[role="button"], input[type="submit"], input[type="button"]'));
                for (const b of candidates) {
                  if (b.offsetParent === null || b.disabled) continue;
                  const txt = (b.innerText || b.textContent || b.value || '').trim().toLowerCase();
                  if (targets.some(t => txt === t || txt.startsWith(t + ' ') || txt.endsWith(' ' + t))) {
                    b.click();
                    return true;
                  }
                }

                // 3. Fallback: Google Material spans inside consent button
                for (const b of candidates) {
                  if (b.offsetParent === null || b.disabled) continue;
                  const spans = b.querySelectorAll('span');
                  for (const s of spans) {
                    const stxt = (s.innerText || s.textContent || '').trim().toLowerCase();
                    if (targets.some(t => stxt === t)) {
                      b.click();
                      return true;
                    }
                  }
                }
              } catch (e) {}
              return false;
            })()
          `)
        } catch {}
      }

      let healedCookieError = false
      const checkCookieError = async () => {
        if (healedCookieError || win.isDestroyed() || resolved) return
        try {
          const isErrorPage = await win.webContents.executeJavaScript(`
            (() => {
              const text = document.body ? (document.body.innerText || '') : '';
              return text.includes('쿠키 설정에 문제가 있음을 발견했습니다') ||
                     text.includes('detected an issue with your cookie settings') ||
                     text.includes('웹브라우저의 쿠키 기능이 사용 중지되어 있습니다');
            })()
          `)
          if (isErrorPage) {
            healedCookieError = true
            console.warn('[Antigravity OAuth IPC] Detected Google cookie rejection. Clearing corrupt session cookies and reloading cleanly...')
            await customSession.clearStorageData({ storages: ['cookies', 'cache'] })
            win.loadURL(authUrl)
          }
        } catch {}
      }

      autoApproveTimer = setInterval(() => {
        tryAutoApprove()
        checkCookieError()
      }, 800)
      win.webContents.on('did-finish-load', () => {
        checkCookieError()
        tryAutoApprove()
      })
      win.webContents.on('did-navigate', () => {
        checkCookieError()
        tryAutoApprove()
      })
      win.webContents.on('did-frame-finish-load', () => {
        checkCookieError()
        tryAutoApprove()
      })

      win.loadURL(authUrl)

      win.on('closed', () => {
        if (autoApproveTimer) clearInterval(autoApproveTimer)
        if (!resolved) {
          resolve({
            success: false,
            message: 'Antigravity 인증 창이 완료되기 전에 닫혔습니다.'
          })
        }
      })
    })
  })

  // 2. Get status for Gemini Web Session
  ipcMain.handle('gemini:get-web-status', async () => {
    const targetDir = getGeminiWebDir()
    const jsonPath = path.join(targetDir, 'cookies_gemini.json')

    if (!fsSync.existsSync(jsonPath)) {
      return { connected: false }
    }

    try {
      const content = await fs.readFile(jsonPath, 'utf-8')
      const data = JSON.parse(content)
      return {
        connected: Boolean(data.secure_1psid),
        email: data.email || 'gemini_user@gmail.com',
        secure1psidMasked: data.secure_1psid ? `${data.secure_1psid.slice(0, 10)}...${data.secure_1psid.slice(-6)}` : '',
        cookieCount: data.cookie_count || (data.cookies ? data.cookies.length : 0),
        updatedAt: data.updated_at || null
      }
    } catch {
      return { connected: false }
    }
  })

  // 3. Clear Gemini Web Session
  ipcMain.handle('gemini:clear-web-session', async () => {
    try {
      const customSession = session.fromPartition(PARTITION_NAME)
      await customSession.clearStorageData({ storages: ['cookies', 'localstorage'] })

      const targetDir = getGeminiWebDir()
      const jsonPath = path.join(targetDir, 'cookies_gemini.json')
      const txtPath = path.join(targetDir, 'cookies_gemini.txt')

      if (fsSync.existsSync(jsonPath)) await fs.unlink(jsonPath)
      if (fsSync.existsSync(txtPath)) await fs.unlink(txtPath)

      return { success: true, message: 'Google Gemini 웹 세션이 초기화되었습니다.' }
    } catch (err) {
      return { success: false, error: err.message }
    }
  })

  // 4. Open Google AI Studio (or Google Cloud Console fallback) window with auto-capture
  ipcMain.handle('gemini:open-aistudio-window', async (_event, emailHint) => {
    const { partition, profile } = await resolvePartitionForTarget(emailHint)
    const customSession = session.fromPartition(partition)

    const modernChromeUA =
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'
    customSession.setUserAgent(modernChromeUA)

    // WebAuthn Passkey modal 방지 (Windows 보안 창 방지)
    customSession.setPermissionRequestHandler((webContents, permission, callback) => {
      if (['security-key', 'u2f', 'webauthn'].includes(permission)) {
        return callback(false)
      }
      callback(true)
    })

    customSession.webRequest.onBeforeSendHeaders(
      { urls: ['https://accounts.google.com/*', 'https://*.google.com/*', 'https://aistudio.google.com/*'] },
      (details, callback) => {
        const headers = { ...details.requestHeaders }
        headers['User-Agent'] = modernChromeUA
        headers['Sec-Ch-Ua'] = '"Chromium";v="136", "Google Chrome";v="136", "Not-A.Brand";v="99"'
        headers['Sec-Ch-Ua-Mobile'] = '?0'
        headers['Sec-Ch-Ua-Platform'] = '"Windows"'
        callback({ cancel: false, requestHeaders: headers })
      }
    )

    let preloadPath = path.join(__dirname, 'login_preload.js')
    if (!fsSync.existsSync(preloadPath)) {
      preloadPath = path.join(__dirname, 'login_preload.mjs')
    }
    if (!fsSync.existsSync(preloadPath)) {
      preloadPath = path.join(app.getAppPath(), 'electron', 'login_preload.js')
    }
    if (!fsSync.existsSync(preloadPath)) {
      preloadPath = path.join(__dirname, '../electron/login_preload.js')
    }

    const win = new BrowserWindow({
      width: 1180,
      height: 840,
      title: `Google AI Studio / Cloud Console API 키 발급 (${profile?.name ? profile.name + ' - ' : ''}${emailHint || 'Google 계정'})`,
      autoHideMenuBar: true,
      webPreferences: {
        session: customSession,
        preload: fsSync.existsSync(preloadPath) ? preloadPath : undefined,
        nodeIntegration: false,
        contextIsolation: true,
        plugins: true,
        webSecurity: true
      }
    })

    win.webContents.setUserAgent(modernChromeUA)

    win.webContents.setWindowOpenHandler(({ url }) => {
      return { action: 'allow' }
    })

    // Support F5 / Ctrl+R reload in AI Studio window
    win.webContents.on('before-input-event', (event, input) => {
      if (input.key === 'F5' || (input.control && input.key.toLowerCase() === 'r')) {
        win.webContents.reload()
      }
    })

    // Direct to AI Studio apikey URL: if unauthenticated, Google redirects naturally with AccountChooser for target email
    const targetEmail = emailHint && emailHint.includes('@') ? emailHint.trim() : (profile?.email || null)
    let targetUrl = 'https://aistudio.google.com/apikey'
    if (targetEmail) {
      targetUrl = `https://accounts.google.com/AccountChooser?Email=${encodeURIComponent(targetEmail)}&continue=${encodeURIComponent('https://aistudio.google.com/apikey')}`
    }

    win.loadURL(targetUrl)

    // Helper banner injection on navigation
    const injectHelperBanner = async () => {
      if (win.isDestroyed()) return
      try {
        await win.webContents.executeJavaScript(`
          (() => {
            // 1. Auto-dismiss cookie consent banner if present
            try {
              const buttons = Array.from(document.querySelectorAll('button, a, span'));
              const agree = buttons.find(b => {
                const t = (b.innerText || b.textContent || '').trim();
                return t === '동의함' || t === 'Accept all' || t.includes('동의함');
              });
              if (agree && typeof agree.click === 'function') {
                agree.click();
              }
            } catch (e) {}

            // 2. Render prominent top navigation & troubleshooting bar
            if (document.getElementById('vl-aistudio-helper-bar')) return;
            const bar = document.createElement('div');
            bar.id = 'vl-aistudio-helper-bar';
            bar.style.position = 'fixed';
            bar.style.top = '10px';
            bar.style.left = '50%';
            bar.style.transform = 'translateX(-50%)';
            bar.style.backgroundColor = 'rgba(15, 23, 42, 0.95)';
            bar.style.backdropFilter = 'blur(10px)';
            bar.style.color = '#f8fafc';
            bar.style.padding = '8px 18px';
            bar.style.borderRadius = '14px';
            bar.style.fontSize = '12px';
            bar.style.fontFamily = 'system-ui, -apple-system, sans-serif';
            bar.style.boxShadow = '0 8px 30px rgba(0,0,0,0.45)';
            bar.style.zIndex = '2147483647';
            bar.style.display = 'flex';
            bar.style.alignItems = 'center';
            bar.style.gap = '10px';
            bar.style.border = '1px solid rgba(56, 189, 248, 0.35)';

            bar.innerHTML = \`
              <span style="font-weight:800;color:#38bdf8;display:flex;align-items:center;gap:4px;">🔑 API 키 연동 도우미</span>
              <span style="color:#94a3b8;font-size:11px;">키 복사 시 자동 저장</span>
              <button id="vl-btn-reload" style="background:#334155;color:#f8fafc;border:1px solid #475569;padding:4px 9px;border-radius:8px;font-size:11px;font-weight:600;cursor:pointer;">
                🔄 새로고침 (F5)
              </button>
              <button id="vl-btn-home" style="background:#0284c7;color:#fff;border:none;padding:4px 9px;border-radius:8px;font-size:11px;font-weight:600;cursor:pointer;" title="구독 오류 시 홈에서 약관 동의를 완료하세요">
                🏠 AI Studio 시작
              </button>
              <button id="vl-btn-switch-gcp" style="background:#059669;color:#fff;border:none;padding:4px 10px;border-radius:8px;font-size:11px;font-weight:700;cursor:pointer;" title="AI Studio 구독 확인이 안될 때 Google Cloud 콘솔에서 즉시 API 키를 생성합니다">
                ☁️ Google Cloud 콘솔에서 발급
              </button>
            \`;
            document.body.appendChild(bar);

            const btnReload = document.getElementById('vl-btn-reload');
            if (btnReload) {
              btnReload.onclick = () => window.location.reload();
            }

            const btnHome = document.getElementById('vl-btn-home');
            if (btnHome) {
              btnHome.onclick = () => {
                window.location.href = 'https://aistudio.google.com/';
              };
            }

            const btnGcp = document.getElementById('vl-btn-switch-gcp');
            if (btnGcp) {
              btnGcp.onclick = () => {
                window.location.href = 'https://console.cloud.google.com/apis/credentials';
              };
            }
          })()
        `)
      } catch {}
    }

    win.webContents.on('did-finish-load', () => injectHelperBanner())
    win.webContents.on('did-navigate', () => injectHelperBanner())
    win.webContents.on('did-navigate-in-page', () => injectHelperBanner())
    win.webContents.on('did-frame-finish-load', () => injectHelperBanner())

    return new Promise((resolve) => {
      let pollInterval = null
      let captured = false
      let initialClipboard = ''
      try {
        initialClipboard = clipboard.readText().trim()
      } catch {}

      const checkKey = async () => {
        if (captured || win.isDestroyed()) return

        try {
          // A. Clipboard detection
          let currentClip = ''
          try {
            currentClip = clipboard.readText().trim()
          } catch {}

          let candidateKey = null
          const keyRegex = /AIzaSy[A-Za-z0-9_-]{33}/

          if (currentClip && currentClip !== initialClipboard && keyRegex.test(currentClip)) {
            const m = currentClip.match(keyRegex)
            if (m) candidateKey = m[0]
          }

          // B. DOM detection in window
          if (!candidateKey) {
            try {
              const domKey = await win.webContents.executeJavaScript(`
                (() => {
                  try {
                    const text = document.body ? document.body.innerText : '';
                    const m = text.match(/AIzaSy[A-Za-z0-9_-]{33}/);
                    return m ? m[0] : null;
                  } catch (e) {
                    return null;
                  }
                })()
              `)
              if (domKey && keyRegex.test(domKey)) {
                candidateKey = domKey
              }
            } catch {}
          }

          if (candidateKey) {
            captured = true
            clearInterval(pollInterval)

            const finalEmail = emailHint || 'gemini_user@gmail.com'
            await notifyBackendAccountKey(finalEmail, candidateKey)

            try {
              await win.webContents.executeJavaScript(`
                (() => {
                  const banner = document.createElement('div');
                  banner.style.position = 'fixed';
                  banner.style.top = '16px';
                  banner.style.left = '50%';
                  banner.style.transform = 'translateX(-50%)';
                  banner.style.backgroundColor = '#059669';
                  banner.style.color = '#ffffff';
                  banner.style.padding = '14px 28px';
                  banner.style.borderRadius = '12px';
                  banner.style.fontSize = '14px';
                  banner.style.fontWeight = 'bold';
                  banner.style.zIndex = '999999999';
                  banner.style.boxShadow = '0 10px 30px rgba(0,0,0,0.5)';
                  banner.innerText = '✅ Google AI Studio API 키 연동 완료! ViraLoop Studio에 저장되었습니다.';
                  document.body.appendChild(banner);
                })()
              `)
            } catch {}

            setTimeout(() => {
              if (!win.isDestroyed()) {
                win.close()
              }
            }, 1500)

            resolve({
              success: true,
              email: finalEmail,
              key: candidateKey,
              masked: candidateKey.slice(0, 8) + '...' + candidateKey.slice(-4),
              message: `Google AI Studio API 키 연동 완료!`
            })
          }
        } catch (err) {
          console.error('[AI Studio Key Window] Check error:', err)
        }
      }

      pollInterval = setInterval(checkKey, 1000)

      win.on('closed', () => {
        if (pollInterval) clearInterval(pollInterval)
        if (!captured) {
          resolve({
            success: false,
            message: 'API 키가 등록되기 전에 창이 닫혔습니다.'
          })
        }
      })
    })
  })
}

