/**
 * Electron IPC Handler - Sovereign OTT Platform Session & Cookie Vault
 * 
 * Supports 6 major OTT platforms:
 * 1. Netflix (넷플릭스)
 * 2. Disney+ (디즈니+)
 * 3. TVING (티빙)
 * 4. Wavve (웨이브)
 * 5. Watcha (왓챠)
 * 6. Coupang Play (쿠팡플레이)
 * 
 * Stores sessions in encrypted, isolated partitions: 'persist:ott_<platform>'
 * Automatically exports cookies to Netscape format txt for yt-dlp, FFmpeg, and sourcing engines.
 */

import { BrowserWindow, session, shell } from 'electron'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import fs from 'node:fs/promises'
import fsSync from 'node:fs'
import os from 'node:os'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

export const OTT_PLATFORMS_CONFIG = {
  netflix: {
    id: 'netflix',
    name: 'Netflix',
    homeUrl: 'https://www.netflix.com/browse',
    loginUrl: 'https://www.netflix.com/login',
    domains: ['.netflix.com', 'netflix.com']
  },
  disney: {
    id: 'disney',
    name: 'Disney+',
    homeUrl: 'https://www.disneyplus.com/home',
    loginUrl: 'https://www.disneyplus.com/login',
    domains: ['.disneyplus.com', 'disneyplus.com']
  },
  tving: {
    id: 'tving',
    name: 'TVING',
    homeUrl: 'https://www.tving.com',
    loginUrl: 'https://www.tving.com/user/login',
    domains: ['.tving.com', 'tving.com']
  },
  wavve: {
    id: 'wavve',
    name: 'Wavve',
    homeUrl: 'https://www.wavve.com',
    loginUrl: 'https://www.wavve.com/member/login',
    domains: ['.wavve.com', 'wavve.com']
  },
  watcha: {
    id: 'watcha',
    name: 'Watcha',
    homeUrl: 'https://watcha.com',
    loginUrl: 'https://watcha.com/sign_in',
    domains: ['.watcha.com', 'watcha.com']
  },
  coupangplay: {
    id: 'coupangplay',
    name: 'Coupang Play',
    homeUrl: 'https://www.coupangplay.com',
    loginUrl: 'https://www.coupangplay.com',
    domains: ['.coupangplay.com', 'coupangplay.com', '.coupang.com', 'coupang.com']
  }
}

/**
 * Get the permanent OTT cookies storage directory
 */
function getOttCookiesDir() {
  const localAppData = process.env.LOCALAPPDATA || path.join(os.homedir(), 'AppData', 'Local')
  const dir = path.join(localAppData, 'ViraLoop Studio', 'media', '04_Profiles', 'ott')
  try {
    fsSync.mkdirSync(dir, { recursive: true })
  } catch (e) {}
  return dir
}

/**
 * Convert Electron Cookie objects to Netscape HTTP Cookie File format
 */
function cookiesToNetscape(cookies, platformName) {
  const lines = [
    '# Netscape HTTP Cookie File',
    `# Generated by ViraLoop Studio for ${platformName}`,
    '# Created at ' + new Date().toISOString(),
    ''
  ]

  for (const c of cookies) {
    const domain = c.domain || ''
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const pathVal = c.path || '/'
    const secure = c.secure ? 'TRUE' : 'FALSE'
    let expiration = Math.floor(c.expirationDate || 0)
    if (expiration <= 0) {
      // 1 year from now for session cookies
      expiration = Math.floor(Date.now() / 1000) + 31536000
    }
    const name = c.name || ''
    const value = c.value || ''
    if (name) {
      lines.append ? lines.push(`${domain}\t${includeSubdomains}\t${pathVal}\t${secure}\t${expiration}\t${name}\t${value}`) : lines.push(`${domain}\t${includeSubdomains}\t${pathVal}\t${secure}\t${expiration}\t${name}\t${value}`)
    }
  }

  return lines.join('\n') + '\n'
}

/**
 * Dump cookies for a partition to file
 */
async function dumpPartitionCookies(platformId) {
  const cfg = OTT_PLATFORMS_CONFIG[platformId]
  if (!cfg) return { success: false, error: 'Unknown platform' }

  try {
    const partitionName = `persist:ott_${platformId}`
    const sess = session.fromPartition(partitionName)
    const cookies = await sess.cookies.get({})
    
    if (!cookies || cookies.length === 0) {
      return { success: false, cookieCount: 0, error: 'No cookies found in partition' }
    }

    const netscapeContent = cookiesToNetscape(cookies, cfg.name)
    const targetDir = getOttCookiesDir()
    const targetPath = path.join(targetDir, `cookies_${platformId}.txt`)
    
    await fs.writeFile(targetPath, netscapeContent, 'utf-8')
    console.log(`[OTT] Dumped ${cookies.length} cookies for ${cfg.name} to ${targetPath}`)
    
    return {
      success: true,
      platform: platformId,
      cookieCount: cookies.length,
      cookieFile: targetPath
    }
  } catch (err) {
    console.error(`[OTT] Failed to dump cookies for ${platformId}:`, err)
    return { success: false, error: err.message }
  }
}

/**
 * Register OTT IPC handlers
 */
export function registerOttIPC(ipcMain) {
  // 1. Open Login Window for OTT platform
  ipcMain.handle('ott:open-login', async (_event, { platform }) => {
    const platformId = (platform || '').toLowerCase().trim()
    const cfg = OTT_PLATFORMS_CONFIG[platformId]
    if (!cfg) {
      return { success: false, error: `지원하지 않는 OTT 플랫폼입니다: ${platform}` }
    }

    const partitionName = `persist:ott_${platformId}`
    const customSession = session.fromPartition(partitionName)

    // Chrome 136 데스크톱 표준 및 Akamai / Cloudflare WAF 안티봇 우회 헤더
    const modernChromeUA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36'
    customSession.setUserAgent(modernChromeUA)

    // Insecure HTTP 방어: Akamai WAF의 평문 HTTP 403 차단 방지를 위해 모든 요청을 HTTPS로 강제 승격
    customSession.webRequest.onBeforeRequest({ urls: ['http://*/*'] }, (details, callback) => {
      const url = details.url || ''
      if (url.includes('coupang') || url.includes('netflix') || url.includes('disney') || url.includes('tving') || url.includes('wavve') || url.includes('watcha')) {
        const secureUrl = url.replace(/^http:\/\//i, 'https://')
        callback({ redirectURL: secureUrl })
        return
      }
      callback({})
    })

    // Sec-Ch-Ua 및 클라이언트 힌트 보정 (Electron 표식 및 X-Requested-With 원천 제거)
    customSession.webRequest.onBeforeSendHeaders((details, callback) => {
      const headers = { ...details.requestHeaders }
      headers['User-Agent'] = modernChromeUA
      headers['Sec-Ch-Ua'] = '"Chromium";v="136", "Google Chrome";v="136", "Not-A.Brand";v="99"'
      headers['Sec-Ch-Ua-Mobile'] = '?0'
      headers['Sec-Ch-Ua-Platform'] = '"Windows"'
      delete headers['X-Requested-With']
      delete headers['x-requested-with']
      if (headers['Referer'] && headers['Referer'].startsWith('http://')) {
        headers['Referer'] = headers['Referer'].replace(/^http:\/\//i, 'https://')
      }
      if (headers['Origin'] && headers['Origin'].startsWith('http://')) {
        headers['Origin'] = headers['Origin'].replace(/^http:\/\//i, 'https://')
      }
      callback({ cancel: false, requestHeaders: headers })
    })

    const preloadPath = path.join(__dirname, '../login_preload.js')

    const win = new BrowserWindow({
      width: 1100,
      height: 800,
      title: `${cfg.name} - ViraLoop Studio 세션 연동 로그인`,
      autoHideMenuBar: true,
      webPreferences: {
        session: customSession,
        preload: fsSync.existsSync(preloadPath) ? preloadPath : undefined,
        nodeIntegration: false,
        contextIsolation: true,
        plugins: true,
        webSecurity: true
      }
    })

    // Load login or home
    win.loadURL(cfg.loginUrl)

    return new Promise((resolve) => {
      let cookieDumpInterval = null

      // Dump periodically while user interacts
      cookieDumpInterval = setInterval(() => {
        dumpPartitionCookies(platformId).catch(() => {})
      }, 5000)

      win.on('closed', async () => {
        if (cookieDumpInterval) clearInterval(cookieDumpInterval)
        // Final dump on window close
        const dumpRes = await dumpPartitionCookies(platformId)
        resolve({
          success: dumpRes.success,
          platform: platformId,
          cookieCount: dumpRes.cookieCount || 0,
          cookieFile: dumpRes.cookieFile || null,
          message: dumpRes.success 
            ? `${cfg.name} 세션 쿠키(${dumpRes.cookieCount}개)가 성공적으로 저장되었습니다.`
            : `${cfg.name} 창이 닫혔습니다. 로그인 여부를 확인하세요.`
        })
      })
    })
  })

  // 2. Get status for all OTT platforms
  ipcMain.handle('ott:get-status', async () => {
    const targetDir = getOttCookiesDir()
    const results = {}

    for (const [id, cfg] of Object.entries(OTT_PLATFORMS_CONFIG)) {
      const filePath = path.join(targetDir, `cookies_${id}.txt`)
      const exists = fsSync.existsSync(filePath)
      let cookieCount = 0
      let updatedAt = null

      if (exists) {
        try {
          const stat = fsSync.statSync(filePath)
          updatedAt = stat.mtime.toISOString().replace('T', ' ').substring(0, 19)
          const content = fsSync.readFileSync(filePath, 'utf-8')
          const lines = content.split('\n').filter(l => l.trim() && !l.startsWith('#'))
          cookieCount = lines.length
        } catch (e) {}
      }

      results[id] = {
        id,
        name: cfg.name,
        homeUrl: cfg.homeUrl,
        loginUrl: cfg.loginUrl,
        exists: exists && cookieCount > 0,
        cookieCount,
        cookieFile: filePath,
        updatedAt,
        status: exists && cookieCount > 0 ? 'ACTIVE' : 'DISCONNECTED'
      }
    }

    return { success: true, platforms: results }
  })

  // 3. Clear OTT session & cookies
  ipcMain.handle('ott:clear-session', async (_event, { platform }) => {
    const platformId = (platform || '').toLowerCase().trim()
    const cfg = OTT_PLATFORMS_CONFIG[platformId]
    if (!cfg) return { success: false, error: 'Unknown platform' }

    try {
      const partitionName = `persist:ott_${platformId}`
      const sess = session.fromPartition(partitionName)
      await sess.clearStorageData()
      await sess.clearCache()

      const targetDir = getOttCookiesDir()
      const filePath = path.join(targetDir, `cookies_${platformId}.txt`)
      if (fsSync.existsSync(filePath)) {
        await fs.unlink(filePath)
      }

      return { success: true, message: `${cfg.name} 세션 및 쿠키가 삭제되었습니다.` }
    } catch (e) {
      return { success: false, error: e.message }
    }
  })

  // 4. Open OTT Cookies directory in File Explorer
  ipcMain.handle('ott:open-folder', async () => {
    try {
      const dir = getOttCookiesDir()
      shell.openPath(dir)
      return { success: true, dir }
    } catch (e) {
      return { success: false, error: e.message }
    }
  })
}
